server:
  port: 8082

spring:
  application:
    name: Invoice Service
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicedb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

axon:
  server:
    enabled: true
    addresses: localhost:8124
  eventhandling:
    processors:
      invoiceProcessor:
        mode: tracking  # optional: enables tracking processors (for queries later)

logging:
  level:
    org.axonframework: DEBUG


